### PR TITLE
Move config.json to config/config.json for Docker-compose compatibility

### PR DESCRIPTION
**Pull request by vista-narvas**
Love the project!  
  
I've made a small enhancement to improve my workflow.  
I've relocated the `config.json` file to `/src/config/config.json` to streamline Docker usage with Portainer.  
This change allows for easy configuration mounting through a volume, eliminating the need for bind mounting files.  
_Note that the file bind mount is still possible, providing flexibility in configuration options._  
  
Looking forward to your feedback!

### CODE REVIEW

**Comment by notclickable-jordan** [comment]
Glad you like the project! I need to clean up the readme.

Your change looks interesting. I use Portainer myself, but only for container monitoring. I've never used it to launch containers. I'm curious why this improves the Portainer experience.

I'm happy to take this change, but it seems like it would require everyone to modify their bind mounts, wouldn't it?

**Comment by vista-narvas** [comment]
> I'm curious why this improves the Portainer experience.

now the only option to mount the config file is to use the file bind mound
with this change its also posible to mound it using a docker volume
docker volumes are more flexible on where the data is stored
its just my prefred way of storing data for docker containers

> it seems like it would require everyone to modify their bind mounts, wouldn't it?

yes, now this change would require that
but i think there is a way for it not to be required,
for example maybe the `/src/config/config.json` file could load `/src/config.json` if it exitsts  
that way people dont need to modify their setup

**Comment by notclickable-jordan** [comment]
I hope you don't mind, but I had to make more changes to get this to work correctly. There were some issues regarding backwards compatibility that I didn't want to go back and forth about. But this is a good addition.

This feature has been implemented in #15 and Docker image version `1.2.0`. Enjoy!

**Comment by vista-narvas** [comment]
No problem at all! Thanks for your for addressing the compatibility issues.

**Pull request closed without merging**
